#!/usr/bin/env python
# Write the next available index value for a directory

import optparse
import os

def main():
    parser = optparse.OptionParser()
    #parser.add_option("-f", "--file", dest="filename",
    #          help="write report to FILE", metavar="FILE")
    #parser.add_option("-q", "--quiet",
    #              action="store_false", dest="verbose", default=True,
    #              help="don't print status messages to stdout")
    parser.add_option("-d", "--dir", dest="dir", default = ".",
                      help="directory to scan. CWD by default")
    parser.add_option("-f", "--full", dest="full", action="store_true", default = False,
                      help="Prepend the specified directory name given by -d option")
    (options, args) = parser.parse_args()    
    dir_list =  os.listdir(options.dir)
    max_index = 0
    for file_name in dir_list:
        try:
            index = int(file_name)
            max_index = max(index, max_index)
        except ValueError:
            pass
    max_index += 1
    
    output = str(max_index)
    if options.full:
        output = options.dir + "/" + output
    print output

if __name__ == "__main__":
    main()
